# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres1:dNMcwotdSgKLQj3jnSm7M5V45Pa9Op4I@dpg-d8nl3ggjs32c73dqqud0-a/clinica_db_zbds
spring.datasource.username=${DB_USER:postgres1}
spring.datasource.password=${DB_PASSWORD:dNMcwotdSgKLQj3jnSm7M5V45Pa9Op4I}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
